### ISSUE TITLE
Perform an infinite loop at 3d text

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-bossmenu#10]
look photo
It turns more than once
It repeats the text
one by one
See the magnitude of the text in the image
https://imgur.com/a/JSzwPiP

**Comment by pushkart2** [comment]
https://github.com/qbcore-framework/qb-bossmenu/blob/b7e24d3492a72e11a286ae3c2ccb00b5c114a351/client/client.lua#L50

Comment this else if condition..
