### ISSUE TITLE
No check for minus values

### ISSUE THREAD

**Issue by ArcadiaRoleplay** [qbcore-framework/qb-bossmenu#12]
When withdrawing if you type for instance -1000 it will add $1000 to the boss menu

**Comment by olegend965** [comment]
also another problem when you try to see the employee menu, it wont show for a code error in client side 127

**Comment by SamShanks1** [comment]
https://github.com/qbcore-framework/qb-bossmenu/commit/48c6dbc64d5baac88dac267cd9bad466ab9211fb

Fixed this
