### ISSUE TITLE
Society issue

### ISSUE THREAD

**Issue by tonibanks** [qbcore-framework/qb-bossmenu#13]
[
![Untitled](https://user-images.githubusercontent.com/54329414/131076752-8bc7b859-3ea6-46b9-97dc-05617ac9da0f.png)
](url)

Having issue bills payment, when i paid the boss society is not updating

**Comment by GhzGarage** [comment]
Seems to me you are not passing amount

**Comment by Mikkelmus** [comment]
i get the samen error what can they be it is a brand new and clean server set up via txadmin 3 hours ago not a single line off code has bin altered .. error occurs when a player pays his bill he has received from a police officer

https://i.imgur.com/URJYStE.png

**Comment by SovietRulez** [comment]
Same issue

**Comment by xenfovn** [comment]
just config job on qb-phone/config.lua
