### ISSUE TITLE
Change color css

### ISSUE THREAD

**Issue by OfficialRDB** [qbcore-framework/qb-bossmenu#18]
Maybe I weird place to ask, because it's not a problem, but I can't find the right place to change the color. Same with the adminmenu. It's all connected with menuv but in there i can't find the proper css.

**Comment by HATE-dev** [comment]
You can see there's 155 ,0 ,0 its basicly r,g,b color codes. Just change them. client.lua
![image](https://user-images.githubusercontent.com/78761393/134992575-6d130c0e-5da1-40bc-93fc-f513ad315670.png)

**Comment by OfficialRDB** [comment]
> 
> 
> You can see there's 155 ,0 ,0 its basicly r,g,b color codes. Just change them. client.lua
> ![image](https://user-images.githubusercontent.com/78761393/134992575-6d130c0e-5da1-40bc-93fc-f513ad315670.png)

Yes, I already changed it in those files, I just wish there was a other way to do it since the menu is getting used in multiple files.
adminmenu
bossmenu
gangmenu

Sure I can just change them all, but why not change it once or read it out of a config that you give one basic color for all the menu's.

But thats just a suggestion. Love QBCore
