### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by Rykamishlava** [qbcore-framework/qb-bossmenu#22]
Hello, you delete my post, but your menu dont work. Go VehicleShop the menu dont showing, only in cops, 0 marker on shop vehicle and on police the marker flash every 1secondes. 

 if your manager in cardealer, the menu dont show.

**Comment by GhzGarage** [comment]
![image](https://user-images.githubusercontent.com/57848836/134092936-59150d97-42f1-4605-b864-7ae69d0bd82a.png)

**Comment by GhzGarage** [comment]
It was just the distance. Re-download

**Comment by Rykamishlava** [comment]
i re-download 3x and i only see the boss menu in cop job :/

**Comment by Rykamishlava** [comment]
YEAAAAAAAAAAAAAH thank you! I change the distance (3) and he work perfect !! Thank men!

**Comment by Rykamishlava** [comment]
![image](https://user-images.githubusercontent.com/15194960/134095027-80b86359-bb43-46ba-b108-bf0427dba030.png)

**Comment by beastmode9185** [comment]
> ![image](https://user-images.githubusercontent.com/57848836/134092936-59150d97-42f1-4605-b864-7ae69d0bd82a.png)

I just updated the boss and gang menu to the latest oxmysql but none of the boss menus respond or open whenever I try and open them
